from module.island.island import *
from time import sleep

class IslandDailyGather(Island):
    def run(self):
        now = datetime.now()
        current_hour = now.hour
        if 0 <= current_hour < 3:
            self.gather_coal()
            self.gather_wood()
            self.gather_farm()
            self.gather_nursery()
            next_run_time = now.replace(hour=3, minute=0, second=0, microsecond=0)
            self.config.task_delay(target=next_run_time)
        elif 3 <= current_hour < 18:
            self.gather_coal()
            self.gather_wood()
            self.gather_farm()
            self.gather_nursery()
            next_run_time = now.replace(hour=18, minute=0, second=0, microsecond=0)
            self.config.task_delay(target=next_run_time)
        elif 18 <= current_hour < 24:
            if self.config.IslandDailyGather_Daily:
                self.gather_wood()
                self.gather_farm()
                self.gather_nursery()
            else:
                self.gather_coal()
                self.gather_wood()
                self.gather_farm()
                self.gather_nursery()
            next_run_time = now.replace(hour=0, minute=0, second=0, microsecond=0)
            next_run_time += timedelta(days=1)
            self.config.task_delay(target=next_run_time)
        self.ui_goto_main()

    def island_gathering(self):
        self.device.click(ISLAND_GATHER_A)
        sleep(0.1)
        self.device.click(ISLAND_GATHER_B)
        sleep(0.1)
        self.device.click(ISLAND_GATHER_C)
        sleep(1.8)
    def gather_wood(self):
        self.island_map_goto('mine_forest')
        self.island_up(2500)
        self.island_gathering()
        self.island_left(500)
        self.island_gathering()
        self.island_up(2000)
        self.island_left(500)
        self.island_up(1000)
        self.island_left(500)
        self.island_up(2600)
        self.island_left(400)
        self.island_gathering()
        self.island_up(2000)
        self.island_gathering()
        self.island_right(500)
        self.island_up(500)
        self.island_gathering()
        self.island_up(1000)
        self.island_gathering()
        self.island_right(700)
        self.island_up(400)
        self.island_gathering()
        self.island_right(700)
        self.island_down(300)
        self.island_gathering()
        self.island_right(1800)
        self.island_down(1300)
        self.island_right(300)
        self.island_gathering()
        self.island_down(2100)
        self.island_left(1600)
        self.island_up(200)
        self.island_gathering()
        self.island_down(1300)
        self.island_right(2200)
        self.island_up(100)
        self.island_gathering()
        self.island_down(1600)
        self.island_left(1500)
        self.island_gathering()
        self.island_right(1000)
        self.island_down(1300)
        self.island_gathering()
        self.island_up(1800)
        self.island_right(1800)
        self.island_gathering()
        self.island_up(800)
        self.island_right(1500)
        self.island_up(300)
        self.island_gathering()
        self.island_right(1900)
        self.island_down(1100)
        self.island_right(1800)
        self.island_down(600)
        self.island_right(1100)
        self.island_gathering()
        self.island_down(600)
        self.island_right(600)
        self.island_gathering()

    def gather_coal(self):
        self.island_map_goto('mine_forest')
        self.island_right(1000)
        self.island_down(3000)
        self.island_right(1200)
        self.island_down(200)
        self.device.click(ISLAND_JUMP)
        self.island_down(3500)
        self.island_gathering()
        self.island_down(2000)
        self.island_gathering()
        self.island_right(600)
        self.device.click(ISLAND_JUMP)
        self.island_right(500)
        sleep(0.5)
        self.island_gathering()
        self.island_right(1500)
        self.island_down(600)
        self.island_gathering()
        self.island_gathering()
        self.island_up(900)
        self.island_gathering()
        self.island_right(800)
        self.island_gathering()
        self.island_up(1300)
        sleep(0.5)
        self.island_down(600)
        self.island_gathering()
        self.island_left(1500)
        self.island_gathering()
        self.island_up(500)
        self.island_left(600)
        self.island_gathering()


    def gather_farm(self):
        self.island_map_goto('farm')
        self.island_up(1100)
        self.island_left(1200)
        self.island_up(2300)
        self.island_left(600)
        self.island_up(1800)
        self.island_left(1100)
        self.island_gathering()
        self.island_up(900)
        self.island_right(300)
        self.island_gathering()
        self.island_right(2200)
        self.island_gathering()
        self.island_down(800)
        self.island_right(3600)
        self.island_down(800)
        self.island_gathering()
        self.island_down(600)
        self.island_right(300)
        self.island_gathering()
        self.island_up(1800)
        self.island_right(1300)
        self.island_gathering()
        self.island_up(600)
        self.island_right(2500)
        self.island_down(800)
        self.island_gathering()
        self.island_right(1500)
        self.island_down(1000)
        self.island_right(300)
        self.island_gathering()
        self.island_down(7600)
        self.island_left(300)
        self.island_gathering()

    def gather_nursery(self):
        self.island_map_goto('nursery')
        self.island_up(4500)
        self.island_right(1000)
        self.island_gathering()

if __name__ == "__main__":
    az =IslandDailyGather('alas', task='Alas')
    az.device.screenshot()
    az.run()